### ISSUE TITLE
Build fails for mjolnir

### ISSUE THREAD

**Issue by niclashoyer** [tomtaylor/valhalla-docker#1]
Trying to run `docker build` I get:

```
configure: error: Could not find valhalla_skadi!
The command '/bin/sh -c cd mjolnir && ./autogen.sh && ./configure CPPFLAGS=-DBOOST_SPIRIT_THREADSAFE && make -j4 && make install && cd ..' returned a non-zero code: 1
```

**Comment by tomtaylor** [comment]
If you've got all the submodules pulled down correctly, it sounds like that might be an issue with the mjolnir project.

**Comment by niclashoyer** [comment]
I just had a look, there seems to be a new repo "skadi" that was missing. Build is running now (not finished yet). I'll add a PR.

**Comment by niclashoyer** [comment]
BTW: shouldn't issues be filed at the valhalla organization, now that it is forked there? Issue functionality is not activated there, though.

**Comment by tomtaylor** [comment]
Ah, OK, thanks - that must be new. 

I'm not sure about the issues. I don't work for Mapzen, and this is my only contribution to the project. I'll speak to someone there and find out what the best approach is.
